language: minimal

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck
before_script:
 - lua gen_option_values.lua
 - /home/travis/.luarocks/bin/luacheck . -q

notifications:
  email:
    on_success: never
    on_failure: always
